version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: marksure-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: marksure
    volumes:
      - mongodb_data:/data/db
      - ./database/seed:/docker-entrypoint-initdb.d
    networks:
      - marksure-network

  # Redis (Optional - for caching)
  redis:
    image: redis:7.2-alpine
    container_name: marksure-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - marksure-network

  # Python AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: marksure-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development
      - API_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./ai-service:/app
      - ./ai-service/temp:/app/temp
      - ./ai-service/models:/app/models
    depends_on:
      - redis
    networks:
      - marksure-network

  # Node.js Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marksure-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/marksure?authSource=admin
      - AI_SERVICE_URL=http://ai-service:8000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      - mongodb
      - redis
      - ai-service
    networks:
      - marksure-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marksure-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - marksure-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  marksure-network:
    driver: bridge